# Versión utilizada
# La versión 3 es la más utilizada y la que se recomienda
version: '3'

# Configuración de los servidores que vamos a necesitar
services:
# mysql es el nombre que vamos a dar a este primer servidor
  # Será el nombre que tendremos que usar cuando nos refiramos a él
  mysql:
    build: mysql/
    ports:
      - 3306:3306
    volumes:
      - ./bbdd:/var/lib/mysql/

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./bbdd:/var/lib/mysql/

  # Apache
  apache:
    build: apache/
    ports:
      - 80:80
    volumes:
      - ./proyecto:/var/www/html/
    depends_on:
      - mysql
    links:
      - mysql

  # PHP
  php:
    build: php/
    ports:
      - 9000:9000
    volumes:
      - ./proyecto:/var/www/html/

volumes:
  bbdd:
  proyecto: